_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en
uuid: b4e84a6a-42d2-4656-b834-877856787d02
name: NewsCT
mail: indranil.roy@gmail.com
slogan: 'We can find daily news here.'
page:
  403: ''
  404: ''
  front: /node
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
